import { Link } from "react-router-dom"
const HeroSection = () => {
  return (
    <>
     <div className="max-w-6xl mx-auto px-8 py-20">
            <div className="text-center">
              <h1 className="text-6xl font-bold mb-6">
                Analyze Your Resume
                <span className="block text-blue-500"> With AI</span>
              </h1>

              <p className="text-gray-400 text-lg max-w-2xl mx-auto mb-10">
                Upload your resume and get an ATS score, strength, missing
                skills, personalized improvements, and interview questions
                generated by AI.
              </p>

              <div className="flex justify-center gap-4 flex-wrap">
                <Link
                  to="/upload"
                  className="inline-block bg-gradient-to-r from-blue-600 to-purple-600 px-8 py-4 rounded-xl text-lg font-semibold hover:scale-105 transition duration-300 shadow-xl"
                >
                  Upload Resume
                </Link>

                <Link
                  to="/history"
                  className="inline-block bg-gradient-to-r from-purple-600 to-pink-600 px-8 py-4 rounded-xl text-lg font-semibold transition duration-300 shadow-xl"
                >
                  Resume History
                </Link>
              </div>
            </div>
          </div>
    </>
  )
}

export default HeroSection
